- .github/workflows/release-with-github.yml
an attempt to add a workflow which allows for releasing new version of an extension by using only UI offered by Github Actions:
> feat(ci): add package releasing workflow via GH UI

- extensions-utils/src/dfx.rs
- extensions-utils/src/download_wasms/nns.rs
- extensions-utils/src/lib.rs
- extensions/nns/src/commands/import.rs
- extensions/nns/src/commands/install.rs
- extensions/nns/src/install_nns.rs
- extensions/nns/src/main.rs
- extensions/sns/src/commands/config/create.rs
- extensions/sns/src/commands/config/mod.rs
- extensions/sns/src/commands/config/validate.rs
- extensions/sns/src/commands/deploy.rs
- extensions/sns/src/commands/download.rs
- extensions/sns/src/commands/import.rs
- extensions/sns/src/create_config.rs
- extensions/sns/src/deploy.rs
- extensions/sns/src/main.rs
- extensions/sns/src/validate_config.rs
implementation of https://github.com/dfinity/sdk/pull/3169
> Some dfx extensions depend on binaries from dfx's cache. Previously, extensions depended on the first dfx in $PATH to locate its cache, which is error-prone for projects that declare a custom dfx version in their dfx.json.
> fix: Accept `dfx` cache path as CLI arg instead of relying on finding first `dfx` in `$PATH`

- extensions/nns/src/commands/install.rs
this fixes the issue where you'd have to write `--ledger-accounts` multiple times
```console
cargo run -p nns install --ledger-accounts fefe --ledger-accounts fefe --dfx-cache-path=$(dfx cache show)
```
```console
cargo run -p nns install --ledger-accounts fefe fefe  --dfx-cache-path=$(dfx cache show)
```
> fix(nns-extension): accept multiple args

- extensions/nns/Cargo.toml
- extensions/sns/Cargo.toml
instead of recently deleted `extension.toml` (in #26)
> fix(release): cargo-release replacement targets `extension.json`

- .github/workflows/release.yml
- Cargo.lock
precursor to https://github.com/dfinity/sdk/pull/2968
Release CI adds a checksum file to Github Release
This will allow us to verify checksum for DFINITY dfx extensions. 
Note: the manifest for external dfx extensions already requires specifying the checksum for the extension archive. 
tested on fork repo: https://github.com/smallstepman/dfx-extensions-fork/releases
> ci(release): add checksum file

- .github/workflows/e2e.yml
- e2e/utils.sh
- extensions-utils/src/project/import.rs
- extensions/nns/e2e/tests/nns.bash
- extensions/sns/e2e/tests/sns.bash
This PR changes the way we install extensions in e2e tests. This will allow us to test the latest changes in the codebase and catch any issues early on.
Instead of running tests against the extension installed from the latest release (by installing tarball from GitHub Releases via `dfx extension install`), we will run tests against extensions built from the source code of the tip of the branch. 
We're building the extension from the source code using cargo-dist (the same thing that we're using in release CI) and installing it manually (without using `dfx extensions install ...`, and instead moving the directory with extension to `$(dfx cache show)/extension`; note: perhaps in the future, it will be a good idea to be able to install the extension directly from archive e.g., `dfx extension …
> test(e2e): test tip of the branch

- extensions/nns/extension.json
The "about" message for nns subcommands was swapped.
> fix: correct the about messages in nns extension.json

- .github/workflows/e2e.yml
- .github/workflows/release-with-github.yml
- .github/workflows/release.yml
- Cargo.toml
Fixes broken e2e tests and release process by upgrading to the newest cargo-dist generated workflow (while preserving all previous functionality, mainly the ability to execute `releaes.yml` workflow from another workflow (`release-with-github.yml`)). 
There are no changes to the release process from the perspective of the process operator.
executed the workflow on fork repo https://github.com/smallstepman/dfx-extensions/pull/5
> fix: e2e workflow and release process

- extensions/nns/e2e/tests/nns.bash
- extensions/nns/src/install_nns.rs
#72's upgrade arg gets ignored by the CMC instead of throwing an error thanks to Candid opt rules.
> fix: uprgade arg with cycles ledger id gets ignored

- extensions-utils/src/dependencies/mod.rs
This makes it so `dfx sns propose` can work with a password-protected identity.  It will require an update to the sns-cli.
Fixes the dfx-extensions side of https://dfinity.atlassian.net/browse/SDK-1475
How I tested this:
From this repo and branch, build and install the sns extension:
```
$ dfx extension install sns --version 0.3.1
$ chmod +w $(dfx cache show)/extensions/sns/sns
$ cargo build
$ cp target/debug/sns $(dfx cache show)/extensions/sns/sns
```
In the IC repo, apply this patch:
```
diff --git a/rs/sns/cli/src/lib.rs b/rs/sns/cli/src/lib.rs
index 3a7eeefc5..769cd8e69 100644
--- a/rs/sns/cli/src/lib.rs
+++ b/rs/sns/cli/src/lib.rs
@@ -625,7 +625,9 @@ impl<'a> RunCommandError<'a> {
fn run_command<'a>(command: &'a [&'a str]) -> Result<(String, String), RunCommandError<'a>> {
let …
```
> fix: for sns propose unable to work with a password-protected identity

- extensions-utils/src/dependencies/download_wasms/nns.rs
- extensions-utils/src/dependencies/mod.rs
There were two issues causing `cargo test` not to pass on my machine:
1. There were some code blocks in doc comments that cargo was interpreting as doctests, but are not valid rust code. I have told cargo to ignore these code blocks by annotating them with `ignore`
2. `test_execute_command_fail` seemed to have different behavior on my machine than on CI, because on my machine `stdout` was coming out to `Some(Null)` instead of `Some(Inherit)`. I don't really understand the significance of that, but I changed the test to ignore the value of this field.
> Make `cargo test` pass

- .github/workflows/build-extension-manually.sh
Exit earlier if the `cargo metadata` call fails, to avoid followup error messages that are not the problem.
Before
```
error: failed to select a version for `candid`.
... required by package `ic-sns-cli v0.9.0 (https://github.com/dfinity/ic?rev=f6a556a24ad934bb33eec0debe3710ce2dbce3ae#f6a556a2)`
... which satisfies git dependency `ic-sns-cli` of package `sns v0.3.1 (/Users/ericswanson/ext/anchpop/dfx-extensions/extensions/sns)`
versions that meet the requirements `^0.10.6` are: 0.10.6
all possible versions conflict with previously selected packages.
previously selected package `candid v0.10.3`
... which satisfies dependency `candid = "^0.10.2"` (locked to 0.10.3) of package `nns v0.3.1 (/Users/ericswanson/ext/anchpop/dfx-extensions/extensions/nns)`
failed to select a version for `candid` …
```
> fix: fail on any error in command pipeline

- Cargo.lock
- Cargo.toml
- extensions/nns/Cargo.toml
- extensions/nns/src/install_nns.rs
This is a follow up to #91 which did the same thing for the sns extension.
> Remove sns-cli embedded binary dependency from NNS 

- Cargo.lock
- extensions/nns/build.rs
- extensions/sns/build.rs
In particular, they are updated to the revision specified in the ic-sns-cli dependency
> Update SNS/NNS replica rev and ic-sns-cli to modern version

- extensions-utils/src/dependencies/download_wasms/mod.rs
This MR makes sure that downloaded canister modules are not ungzipped as their ungzipped size could be too big for the canister modules to be deployed on the IC.
> fix: do not ungzip canister modules

- .github/workflows/release.yml
- Cargo.toml
In "plan" pr-run-mode, cargo-dist doesn't have a pr-run-mode that can handle different projects in a repo that have different version numbers.  See https://github.com/axodotdev/cargo-dist/issues/905
This means that a PR that updates the version of only one extension or updates to distinct versions will always fail CI.  The workflow prior to https://github.com/dfinity/dfx-extensions/pull/85 also skipped this step for PRs, though this was done by hand-editing the .yml file, rather than through settings in Cargo.toml, so it wasn't obvious.
> fix: allow version numbers to diverge

- Cargo.lock
- Cargo.toml
- extensions/nns/build.rs
- extensions/nns/src/install_nns.rs
- extensions/sns/CHANGELOG.md
- extensions/sns/build.rs
- Update changelogs
- Update replica rev
- Fix a compilation error that may have been caused by a backwards-incompatible change in `ic_icrc1_index_ng`
> Prepare for 0.4.1 upgrade

- Cargo.lock
- Cargo.toml
- extensions/nns/build.rs
- extensions/sns/CHANGELOG.md
- extensions/sns/README.md
- extensions/sns/build.rs
- extensions/sns/e2e/tests/sns.bash
- extensions/sns/extension.json
- extensions/sns/src/main.rs
Pretty much all the implementation is already done in the ic repo, we just need to hook it up to the dfx extension
> Add support for the "neuron-id-to-candid-subaccount" command

- Cargo.lock
- Cargo.toml
- extensions/nns/build.rs
- extensions/sns/CHANGELOG.md
- extensions/sns/build.rs
- extensions/sns/e2e/tests/sns.bash
- extensions/sns/extension.json
This adds a "confirmation text" to the `propose` command (to make sure users know what they're getting themselves into before proposing an SNS). Once this is merged, the extension will be ready for the 0.4.2 release, but it shouldn't actually be released until a new version of SNS Governance is released.
> Upgrade to newer git rev

- extensions-utils/src/dependencies/download_wasms/sns.rs
`dfx sns download` downloads specified versions of the SNS canister wasms. However, it currently downloads the `index` canister wasm, while the sns uses `index-ng`. This PR fixes this discrepancy
> Download index-ng instead of index

- Cargo.lock
- Cargo.toml
- extensions-utils/Cargo.toml
- extensions-utils/src/lib.rs
- extensions-utils/src/manifest.rs
- extensions/nns/build.rs
- extensions/sns/Cargo.toml
- extensions/sns/build.rs
- extensions/sns/e2e/assets/sns/valid/sns_init.yaml
- extensions/sns/src/main.rs
With this PR, the `sns` DFX extension's `extension.json` can now be automatically updated by running `cargo test`. If the extension.json has been updated, the test fails, so CI will fail if you try to commit a change that requires a change to extension.json. This means that the developer can just run `cargo test` before committing, which will fail the first time and then succeed the second time. This may be slightly unintuitive but I think it is a good developer experience, as they'll likely run `cargo test` at least once during development anyway.
I plan to add this for the `nns` extension as well at some point.
> refactor: Automatically update the SNS extension's extension.json

- extensions/nns/src/install_nns.rs
This MR fixes the URLs in the nns-dapp init args to always point to localhost:8080 since the nns extension assumes that there's an HTTP gateway listening at localhost:8080 and pointing to the local replica (`nns_url`) breaks the nns-dapp if a user restarts the replica without a pinned replica port (since the replica port likely changes and the hard-coded URLs for the stopped replica become invalid).
> fix: use localhost:8080 in nns-dapp init args

- .github/workflows/e2e.yml
Use the command specified at https://github.com/axodotdev/cargo-dist/releases/tag/v0.10.0 to install cargo-dist.
Intended to reduce CI failures seen when using cargo-binstall
> fix: use cargo-dist install script

- Cargo.lock
- Cargo.toml
- extensions/nns/Cargo.toml
- extensions/nns/build.rs
- extensions/nns/src/install_nns.rs
- extensions/sns/Cargo.toml
- extensions/sns/README.md
- extensions/sns/build.rs
- extensions/sns/e2e/tests/sns.bash
- extensions/sns/extension.json
- extensions/sns/src/main.rs
- extensions/sns/src/utils.rs
This brings it in sync with the monorepo's sns cli. 
`add-sns-wasm-for-tests` is hidden as it's relatively "developer only" and I don't have a good idea of when it's needed, other than that I know snsdemo uses it.
The commands were implemented in the monorepo, and are just called from here.
> feat(sns): Add `list` and `add-sns-wasm-for-tests` command

- extensions/sns/e2e/tests/sns.bash
- extensions/sns/src/commands/download.rs
- extensions/sns/src/commands/import.rs
- extensions/sns/src/main.rs
This was causing an issue with `sns import` and `sns download` as creating a runtime within a runtime is unsupported. It's nice when you can remove code to fix a bug :)
> refactor: avoid using block_on when we already have an async runtime

- Cargo.lock
- Cargo.toml
- extensions/nns/build.rs
- extensions/sns/build.rs
This updates the replica rev to the latest version, since the previous version of the DFX NNS extension used a version of NNS Governance that removed support for some proposal types. The IC monorepo version is also updated as it needs to be kept in sync with the replica rev.
> Update replica rev / IC monorepo version

- Cargo.lock
- Cargo.toml
- extensions/nns/build.rs
- extensions/sns/README.md
- extensions/sns/build.rs
- extensions/sns/extension.json
- extensions/sns/src/main.rs
Use the `dfx sns health` command to see the health of all SNSes. You can also pass `--json` to get this information in json format rather than a human-readable table. By default, dapp canisters are not examined. You can include them with the `--include-dapps` subcommand.
This command is implemented in the IC monorepo, so all that is required of the extension is to call the appropriate function in the monorepo.
> feat(sns): Add `health` command

- .github/workflows/e2e.yml
- Cargo.lock
- Cargo.toml
- extensions/nns/CHANGELOG.md
- extensions/nns/e2e/tests/nns.bash
- extensions/nns/src/commands/import.rs
- extensions/nns/src/commands/install.rs
- extensions/sns/CHANGELOG.md
- extensions/sns/src/commands/import.rs
`dfx nns install`, `dfx nns import`, and `dfx sns import` all load dfx.json if present.  If dfx.json includes a canister with a type defined by an extension, the config loader won't recognize the type unless we provide an ExtensionManager.  This PR provides the needed ExtensionManager.
Fixes https://dfinity.atlassian.net/browse/SDK-1832
> fix: load dfx.json with extension-defined canister type

- extensions/nns/CHANGELOG.md
- extensions/nns/e2e/assets/subnet_type/shared_network_settings/application/networks.json
- extensions/nns/e2e/tests/nns.bash
- extensions/nns/src/install_nns.rs
- extensions/sns/src/main.rs
This PR adds support for application subnets when using `dfx start --pocketic`.
> feat: support application subnets for PocketIC

- .github/workflows/e2e.yml
- Cargo.lock
- Cargo.toml
- extensions/nns/CHANGELOG.md
- extensions/nns/Cargo.toml
- extensions/nns/e2e/tests/nns.bash
- extensions/nns/src/install_nns.rs
This PR sonfigures the PocketIC SNS subnet in the SNS-W canister and the PocketIC default subnet in the CMC canister by reading the subnet IDs from the PocketIC topology.
> feat: configure PocketIC SNS and PocketIC default subnet in NNS canisters

- .github/workflows/build-extension-manually.sh
workspace_members can contain something like `path+file:///Users/ericswanson/fork/anchpop/dfx-extensions/extensions/nns#0.4.7` when run on a branch on a fork.
Instead, get the version directly from the package.
> fix: obtain extension version even on branch on a fork

- extensions/nns/extension.json
- extensions/nns/src/install_nns.rs
Exchange rate proposal is deprecated and will not be able to get created soon. Instead, the CMC is always initialized with a default rate, which makes the initial proposal unnecessary.
* Stop calling `set_xdr_rate` and remove the function.
* Update `dependencies.dfx` in `extensions/nns/extension.json`
* 0.24.1 is the first version with replica_rev containing [this commit](https://github.com/dfinity/ic/commit/94f580d004c5e24f4f51b525e8f8273f7d6265bc)
> Stop sending exchange rate proposal as part of NNS setup

- extensions-utils/src/dependencies/dfx.rs
- extensions-utils/src/dependencies/download_wasms/nns.rs
- extensions-utils/src/lib.rs
- extensions/nns/build.rs
- extensions/nns/src/commands/import.rs
- extensions/sns/build.rs
- extensions/sns/src/commands/download.rs
- extensions/sns/src/commands/import.rs
- extensions/sns/src/main.rs
The binaries and wasms used by the NNS/SNS extensions are using different versions - the wasms mostly use the `dfx info replica-rev` selected by the dfx release, while the binaries (such as ic_nns_init) are using the hard-coded one. However, there are dependencies among them, and it's difficult to maintain compatibility when they are chosen by disjoint release processes.
* Define a variable `NNS_SNS_REPLICA_REV`
* Replace usage of `replica_rev(dfx_cache_path)` with `NNS_SNS_REPLICA_REV`
* Replace usage of `REPLICA_REV` with `NNS_SNS_REPLICA_REV`
* Update the replica rev to 5ebf5a3922383cbb937d0fbc0509aec445341036 (where the icrc1 ledger index has the correct path)
The intention is to make it clear that this git hash is for choosing NNS/SNS binaries/wasms, without precluding the …
> Use the same replica rev for NNS/SNS extension binaries/wasms

- .github/workflows/e2e.yml
The ubuntu-20.04 runner is obsolete: https://github.com/actions/runner-images/issues/11101
Replace "ubuntu-20.04" with "ubuntu-22.04" in e2e.yml
> chore: Use ubuntu 22.04 runner for e2e testing

- CODEOWNERS
dfinity/nns-team is renamed to dfinity/governance-team. Update CODEOWNERS accordingly.
> chore: Fix CODEOWNERS after renaming from nns-team to governance-team

- dist-workspace.toml
Previously, only the "global" runner is set to "ubuntu-22.04", while the linux runner is still the default (set by `cargo-dist`) "ubuntu-20.04". 
Previously, [this job](https://github.com/dfinity/dfx-extensions/actions/runs/15234019319/job/42845503695) runs `dist host --steps=create --tag=nns-v0.5.2 --output-format=json` and its output is incorrect because "ubuntu-20.04" is still specified as the runner for "x86_64-unknown-linux-gnu". With this change, running `dist host --steps=create --tag=nns-v0.5.2 --output-format=json` locally produces the right result - the "x86_64-unknown-linux-gnu" is set to "ubuntu-22.04"
> chore: Specify the custom runner for x86_64-unknown-linux-gnu too

- extensions/sns/extension.json
`dfx sns ${COMMAND}` uses the extension.json to validate the args. Previously, the `network` arg was missing for several commands even though it's accepted by the extension binary (most likely overlooked as `network` applies to all subcommands). This PR adds the network arg for most of the commands. Note that it's not added for `download`/`import` since they do not interact with the IC network.
> fix: Add the network arg into SNS extension json

- Cargo.lock
- Cargo.toml
`pocket-ic` v10 introduced breaking changes.
As we want to bump the `dfx` bundled `pocket-ic` to the latest, we need to bump the `pocket-ic` in extensions.
This sdk [PR](https://github.com/dfinity/sdk/pull/4376) provides more context.
> chore: bump pocket-ic to v10
